// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ComponentResponse implements flatbuffers.IUnpackableObject<ComponentResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentResponse(bb:flatbuffers.ByteBuffer, obj?:ComponentResponse):ComponentResponse {
  return (obj || new ComponentResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentResponse(bb:flatbuffers.ByteBuffer, obj?:ComponentResponse):ComponentResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

keyLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

keyArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

values(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

valuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valuesArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startComponentResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static createKeyVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startKeyVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valuesOffset, 0);
}

static createValuesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endComponentResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentResponse(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, valuesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ComponentResponse.startComponentResponse(builder);
  ComponentResponse.addKey(builder, keyOffset);
  ComponentResponse.addValues(builder, valuesOffset);
  return ComponentResponse.endComponentResponse(builder);
}

unpack(): ComponentResponseT {
  return new ComponentResponseT(
    this.bb!.createScalarList<number>(this.key.bind(this), this.keyLength()),
    this.bb!.createScalarList<number>(this.values.bind(this), this.valuesLength())
  );
}


unpackTo(_o: ComponentResponseT): void {
  _o.key = this.bb!.createScalarList<number>(this.key.bind(this), this.keyLength());
  _o.values = this.bb!.createScalarList<number>(this.values.bind(this), this.valuesLength());
}
}

export class ComponentResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public key: (number)[] = [],
  public values: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = ComponentResponse.createKeyVector(builder, this.key);
  const values = ComponentResponse.createValuesVector(builder, this.values);

  return ComponentResponse.createComponentResponse(builder,
    key,
    values
  );
}
}
