// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ApplicationMessage, ApplicationMessageT } from '../../schemas/host/application-message';
import { GetSecretRequest, GetSecretRequestT } from '../../schemas/host/get-secret-request';
import { OutboundComponentMsgType, unionToOutboundComponentMsgType, unionListToOutboundComponentMsgType } from '../../schemas/host/outbound-component-msg-type';
import { RandomBytesRequest, RandomBytesRequestT } from '../../schemas/host/random-bytes-request';
import { RequestUserInput, RequestUserInputT } from '../../schemas/host/request-user-input';
import { SetSecretRequest, SetSecretRequestT } from '../../schemas/host/set-secret-request';


export class OutboundComponentMsg implements flatbuffers.IUnpackableObject<OutboundComponentMsgT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OutboundComponentMsg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOutboundComponentMsg(bb:flatbuffers.ByteBuffer, obj?:OutboundComponentMsg):OutboundComponentMsg {
  return (obj || new OutboundComponentMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOutboundComponentMsg(bb:flatbuffers.ByteBuffer, obj?:OutboundComponentMsg):OutboundComponentMsg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OutboundComponentMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

inboundType():OutboundComponentMsgType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : OutboundComponentMsgType.NONE;
}

inbound(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startOutboundComponentMsg(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addInboundType(builder:flatbuffers.Builder, inboundType:OutboundComponentMsgType) {
  builder.addFieldInt8(0, inboundType, OutboundComponentMsgType.NONE);
}

static addInbound(builder:flatbuffers.Builder, inboundOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, inboundOffset, 0);
}

static endOutboundComponentMsg(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOutboundComponentMsg(builder:flatbuffers.Builder, inboundType:OutboundComponentMsgType, inboundOffset:flatbuffers.Offset):flatbuffers.Offset {
  OutboundComponentMsg.startOutboundComponentMsg(builder);
  OutboundComponentMsg.addInboundType(builder, inboundType);
  OutboundComponentMsg.addInbound(builder, inboundOffset);
  return OutboundComponentMsg.endOutboundComponentMsg(builder);
}

unpack(): OutboundComponentMsgT {
  return new OutboundComponentMsgT(
    this.inboundType(),
    (() => {
      const temp = unionToOutboundComponentMsgType(this.inboundType(), this.inbound.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: OutboundComponentMsgT): void {
  _o.inboundType = this.inboundType();
  _o.inbound = (() => {
      const temp = unionToOutboundComponentMsgType(this.inboundType(), this.inbound.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class OutboundComponentMsgT implements flatbuffers.IGeneratedObject {
constructor(
  public inboundType: OutboundComponentMsgType = OutboundComponentMsgType.NONE,
  public inbound: ApplicationMessageT|GetSecretRequestT|RandomBytesRequestT|RequestUserInputT|SetSecretRequestT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const inbound = builder.createObjectOffset(this.inbound);

  return OutboundComponentMsg.createOutboundComponentMsg(builder,
    this.inboundType,
    inbound
  );
}
}
