// automatically generated by the FlatBuffers compiler, do not modify

import { ApplicationMessage, ApplicationMessageT } from '../../schemas/host/application-message';
import { GetSecretRequest, GetSecretRequestT } from '../../schemas/host/get-secret-request';
import { RandomBytesRequest, RandomBytesRequestT } from '../../schemas/host/random-bytes-request';
import { RequestUserInput, RequestUserInputT } from '../../schemas/host/request-user-input';
import { SetSecretRequest, SetSecretRequestT } from '../../schemas/host/set-secret-request';


export enum OutboundComponentMsgType {
  NONE = 0,
  ApplicationMessage = 1,
  RequestUserInput = 2,
  GetSecretRequest = 3,
  SetSecretRequest = 4,
  RandomBytesRequest = 5
}

export function unionToOutboundComponentMsgType(
  type: OutboundComponentMsgType,
  accessor: (obj:ApplicationMessage|GetSecretRequest|RandomBytesRequest|RequestUserInput|SetSecretRequest) => ApplicationMessage|GetSecretRequest|RandomBytesRequest|RequestUserInput|SetSecretRequest|null
): ApplicationMessage|GetSecretRequest|RandomBytesRequest|RequestUserInput|SetSecretRequest|null {
  switch(OutboundComponentMsgType[type]) {
    case 'NONE': return null; 
    case 'ApplicationMessage': return accessor(new ApplicationMessage())! as ApplicationMessage;
    case 'RequestUserInput': return accessor(new RequestUserInput())! as RequestUserInput;
    case 'GetSecretRequest': return accessor(new GetSecretRequest())! as GetSecretRequest;
    case 'SetSecretRequest': return accessor(new SetSecretRequest())! as SetSecretRequest;
    case 'RandomBytesRequest': return accessor(new RandomBytesRequest())! as RandomBytesRequest;
    default: return null;
  }
}

export function unionListToOutboundComponentMsgType(
  type: OutboundComponentMsgType, 
  accessor: (index: number, obj:ApplicationMessage|GetSecretRequest|RandomBytesRequest|RequestUserInput|SetSecretRequest) => ApplicationMessage|GetSecretRequest|RandomBytesRequest|RequestUserInput|SetSecretRequest|null, 
  index: number
): ApplicationMessage|GetSecretRequest|RandomBytesRequest|RequestUserInput|SetSecretRequest|null {
  switch(OutboundComponentMsgType[type]) {
    case 'NONE': return null; 
    case 'ApplicationMessage': return accessor(index, new ApplicationMessage())! as ApplicationMessage;
    case 'RequestUserInput': return accessor(index, new RequestUserInput())! as RequestUserInput;
    case 'GetSecretRequest': return accessor(index, new GetSecretRequest())! as GetSecretRequest;
    case 'SetSecretRequest': return accessor(index, new SetSecretRequest())! as SetSecretRequest;
    case 'RandomBytesRequest': return accessor(index, new RandomBytesRequest())! as RandomBytesRequest;
    default: return null;
  }
}
