// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ContractInstanceId, ContractInstanceIdT } from '../../schemas/host/contract-instance-id';
import { State, StateT } from '../../schemas/host/state';
import { StateDelta, StateDeltaT } from '../../schemas/host/state-delta';


export class StateDeltaWithContractInstanceUpdate implements flatbuffers.IUnpackableObject<StateDeltaWithContractInstanceUpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StateDeltaWithContractInstanceUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStateDeltaWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:StateDeltaWithContractInstanceUpdate):StateDeltaWithContractInstanceUpdate {
  return (obj || new StateDeltaWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStateDeltaWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:StateDeltaWithContractInstanceUpdate):StateDeltaWithContractInstanceUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateDeltaWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

relatedTo(obj?:ContractInstanceId):ContractInstanceId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

state(obj?:State):State|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

delta(obj?:StateDelta):StateDelta|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new StateDelta()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startStateDeltaWithContractInstanceUpdate(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRelatedTo(builder:flatbuffers.Builder, relatedToOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, relatedToOffset, 0);
}

static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stateOffset, 0);
}

static addDelta(builder:flatbuffers.Builder, deltaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, deltaOffset, 0);
}

static endStateDeltaWithContractInstanceUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): StateDeltaWithContractInstanceUpdateT {
  return new StateDeltaWithContractInstanceUpdateT(
    (this.relatedTo() !== null ? this.relatedTo()!.unpack() : null),
    (this.state() !== null ? this.state()!.unpack() : null),
    (this.delta() !== null ? this.delta()!.unpack() : null)
  );
}


unpackTo(_o: StateDeltaWithContractInstanceUpdateT): void {
  _o.relatedTo = (this.relatedTo() !== null ? this.relatedTo()!.unpack() : null);
  _o.state = (this.state() !== null ? this.state()!.unpack() : null);
  _o.delta = (this.delta() !== null ? this.delta()!.unpack() : null);
}
}

export class StateDeltaWithContractInstanceUpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public relatedTo: ContractInstanceIdT|null = null,
  public state: StateT|null = null,
  public delta: StateDeltaT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const relatedTo = (this.relatedTo !== null ? this.relatedTo!.pack(builder) : 0);
  const state = (this.state !== null ? this.state!.pack(builder) : 0);
  const delta = (this.delta !== null ? this.delta!.pack(builder) : 0);

  StateDeltaWithContractInstanceUpdate.startStateDeltaWithContractInstanceUpdate(builder);
  StateDeltaWithContractInstanceUpdate.addRelatedTo(builder, relatedTo);
  StateDeltaWithContractInstanceUpdate.addState(builder, state);
  StateDeltaWithContractInstanceUpdate.addDelta(builder, delta);

  return StateDeltaWithContractInstanceUpdate.endStateDeltaWithContractInstanceUpdate(builder);
}
}
