// automatically generated by the FlatBuffers compiler, do not modify

import { ContractV1, ContractV1T } from '../../schemas/host/contract-v1';


export enum WasmContract {
  NONE = 0,
  ContractV1 = 1
}

export function unionToWasmContract(
  type: WasmContract,
  accessor: (obj:ContractV1) => ContractV1|null
): ContractV1|null {
  switch(WasmContract[type]) {
    case 'NONE': return null; 
    case 'ContractV1': return accessor(new ContractV1())! as ContractV1;
    default: return null;
  }
}

export function unionListToWasmContract(
  type: WasmContract, 
  accessor: (index: number, obj:ContractV1) => ContractV1|null, 
  index: number
): ContractV1|null {
  switch(WasmContract[type]) {
    case 'NONE': return null; 
    case 'ContractV1': return accessor(index, new ContractV1())! as ContractV1;
    default: return null;
  }
}
