// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace CommonDefinitions{
export enum WasmContract{
  NONE= 0,
  ContractV1= 1
};

export function unionToWasmContract(
  type: WasmContract,
  accessor: (obj:CommonDefinitions.ContractV1) => CommonDefinitions.ContractV1|null
): CommonDefinitions.ContractV1|null {
  switch(CommonDefinitions.WasmContract[type]) {
    case 'NONE': return null; 
    case 'ContractV1': return accessor(new CommonDefinitions.ContractV1())! as CommonDefinitions.ContractV1;
    default: return null;
  }
}

export function unionListToWasmContract(
  type: WasmContract, 
  accessor: (index: number, obj:CommonDefinitions.ContractV1) => CommonDefinitions.ContractV1|null, 
  index: number
): CommonDefinitions.ContractV1|null {
  switch(CommonDefinitions.WasmContract[type]) {
    case 'NONE': return null; 
    case 'ContractV1': return accessor(index, new CommonDefinitions.ContractV1())! as CommonDefinitions.ContractV1;
    default: return null;
  }
}
}

/**
 * @enum {number}
 */
export namespace CommonDefinitions{
export enum UpdateData{
  NONE= 0,
  StateUpdate= 1,
  DeltaUpdate= 2,
  StateDeltaUpdate= 3,
  StateWithContractInstanceUpdate= 4,
  DeltaWithContractInstanceUpdate= 5,
  StateDeltaWithContractInstanceUpdate= 6
};

export function unionToUpdateData(
  type: UpdateData,
  accessor: (obj:CommonDefinitions.DeltaUpdate|CommonDefinitions.DeltaWithContractInstanceUpdate|CommonDefinitions.StateDeltaUpdate|CommonDefinitions.StateDeltaWithContractInstanceUpdate|CommonDefinitions.StateUpdate|CommonDefinitions.StateWithContractInstanceUpdate) => CommonDefinitions.DeltaUpdate|CommonDefinitions.DeltaWithContractInstanceUpdate|CommonDefinitions.StateDeltaUpdate|CommonDefinitions.StateDeltaWithContractInstanceUpdate|CommonDefinitions.StateUpdate|CommonDefinitions.StateWithContractInstanceUpdate|null
): CommonDefinitions.DeltaUpdate|CommonDefinitions.DeltaWithContractInstanceUpdate|CommonDefinitions.StateDeltaUpdate|CommonDefinitions.StateDeltaWithContractInstanceUpdate|CommonDefinitions.StateUpdate|CommonDefinitions.StateWithContractInstanceUpdate|null {
  switch(CommonDefinitions.UpdateData[type]) {
    case 'NONE': return null; 
    case 'StateUpdate': return accessor(new CommonDefinitions.StateUpdate())! as CommonDefinitions.StateUpdate;
    case 'DeltaUpdate': return accessor(new CommonDefinitions.DeltaUpdate())! as CommonDefinitions.DeltaUpdate;
    case 'StateDeltaUpdate': return accessor(new CommonDefinitions.StateDeltaUpdate())! as CommonDefinitions.StateDeltaUpdate;
    case 'StateWithContractInstanceUpdate': return accessor(new CommonDefinitions.StateWithContractInstanceUpdate())! as CommonDefinitions.StateWithContractInstanceUpdate;
    case 'DeltaWithContractInstanceUpdate': return accessor(new CommonDefinitions.DeltaWithContractInstanceUpdate())! as CommonDefinitions.DeltaWithContractInstanceUpdate;
    case 'StateDeltaWithContractInstanceUpdate': return accessor(new CommonDefinitions.StateDeltaWithContractInstanceUpdate())! as CommonDefinitions.StateDeltaWithContractInstanceUpdate;
    default: return null;
  }
}

export function unionListToUpdateData(
  type: UpdateData, 
  accessor: (index: number, obj:CommonDefinitions.DeltaUpdate|CommonDefinitions.DeltaWithContractInstanceUpdate|CommonDefinitions.StateDeltaUpdate|CommonDefinitions.StateDeltaWithContractInstanceUpdate|CommonDefinitions.StateUpdate|CommonDefinitions.StateWithContractInstanceUpdate) => CommonDefinitions.DeltaUpdate|CommonDefinitions.DeltaWithContractInstanceUpdate|CommonDefinitions.StateDeltaUpdate|CommonDefinitions.StateDeltaWithContractInstanceUpdate|CommonDefinitions.StateUpdate|CommonDefinitions.StateWithContractInstanceUpdate|null, 
  index: number
): CommonDefinitions.DeltaUpdate|CommonDefinitions.DeltaWithContractInstanceUpdate|CommonDefinitions.StateDeltaUpdate|CommonDefinitions.StateDeltaWithContractInstanceUpdate|CommonDefinitions.StateUpdate|CommonDefinitions.StateWithContractInstanceUpdate|null {
  switch(CommonDefinitions.UpdateData[type]) {
    case 'NONE': return null; 
    case 'StateUpdate': return accessor(index, new CommonDefinitions.StateUpdate())! as CommonDefinitions.StateUpdate;
    case 'DeltaUpdate': return accessor(index, new CommonDefinitions.DeltaUpdate())! as CommonDefinitions.DeltaUpdate;
    case 'StateDeltaUpdate': return accessor(index, new CommonDefinitions.StateDeltaUpdate())! as CommonDefinitions.StateDeltaUpdate;
    case 'StateWithContractInstanceUpdate': return accessor(index, new CommonDefinitions.StateWithContractInstanceUpdate())! as CommonDefinitions.StateWithContractInstanceUpdate;
    case 'DeltaWithContractInstanceUpdate': return accessor(index, new CommonDefinitions.DeltaWithContractInstanceUpdate())! as CommonDefinitions.DeltaWithContractInstanceUpdate;
    case 'StateDeltaWithContractInstanceUpdate': return accessor(index, new CommonDefinitions.StateDeltaWithContractInstanceUpdate())! as CommonDefinitions.StateDeltaWithContractInstanceUpdate;
    default: return null;
  }
}
}

/**
 * @enum {number}
 */
export namespace HostResponseSchema{
export enum Response{
  NONE= 0,
  HostError= 1,
  PutResponse= 2,
  UpdateResponse= 3,
  GetResponse= 4,
  UpdateNotification= 5
};

export function unionToResponse(
  type: Response,
  accessor: (obj:HostResponseSchema.GetResponse|HostResponseSchema.HostError|HostResponseSchema.PutResponse|HostResponseSchema.UpdateNotification|HostResponseSchema.UpdateResponse) => HostResponseSchema.GetResponse|HostResponseSchema.HostError|HostResponseSchema.PutResponse|HostResponseSchema.UpdateNotification|HostResponseSchema.UpdateResponse|null
): HostResponseSchema.GetResponse|HostResponseSchema.HostError|HostResponseSchema.PutResponse|HostResponseSchema.UpdateNotification|HostResponseSchema.UpdateResponse|null {
  switch(HostResponseSchema.Response[type]) {
    case 'NONE': return null; 
    case 'HostError': return accessor(new HostResponseSchema.HostError())! as HostResponseSchema.HostError;
    case 'PutResponse': return accessor(new HostResponseSchema.PutResponse())! as HostResponseSchema.PutResponse;
    case 'UpdateResponse': return accessor(new HostResponseSchema.UpdateResponse())! as HostResponseSchema.UpdateResponse;
    case 'GetResponse': return accessor(new HostResponseSchema.GetResponse())! as HostResponseSchema.GetResponse;
    case 'UpdateNotification': return accessor(new HostResponseSchema.UpdateNotification())! as HostResponseSchema.UpdateNotification;
    default: return null;
  }
}

export function unionListToResponse(
  type: Response, 
  accessor: (index: number, obj:HostResponseSchema.GetResponse|HostResponseSchema.HostError|HostResponseSchema.PutResponse|HostResponseSchema.UpdateNotification|HostResponseSchema.UpdateResponse) => HostResponseSchema.GetResponse|HostResponseSchema.HostError|HostResponseSchema.PutResponse|HostResponseSchema.UpdateNotification|HostResponseSchema.UpdateResponse|null, 
  index: number
): HostResponseSchema.GetResponse|HostResponseSchema.HostError|HostResponseSchema.PutResponse|HostResponseSchema.UpdateNotification|HostResponseSchema.UpdateResponse|null {
  switch(HostResponseSchema.Response[type]) {
    case 'NONE': return null; 
    case 'HostError': return accessor(index, new HostResponseSchema.HostError())! as HostResponseSchema.HostError;
    case 'PutResponse': return accessor(index, new HostResponseSchema.PutResponse())! as HostResponseSchema.PutResponse;
    case 'UpdateResponse': return accessor(index, new HostResponseSchema.UpdateResponse())! as HostResponseSchema.UpdateResponse;
    case 'GetResponse': return accessor(index, new HostResponseSchema.GetResponse())! as HostResponseSchema.GetResponse;
    case 'UpdateNotification': return accessor(index, new HostResponseSchema.UpdateNotification())! as HostResponseSchema.UpdateNotification;
    default: return null;
  }
}
}

/**
 * @constructor
 */
export namespace CommonDefinitions{
export class ContractInstanceId {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ContractInstanceId
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ContractInstanceId {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ContractInstanceId= obj
 * @returns ContractInstanceId
 */
static getRootAsContractInstanceId(bb:flatbuffers.ByteBuffer, obj?:ContractInstanceId):ContractInstanceId {
  return (obj || new ContractInstanceId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ContractInstanceId= obj
 * @returns ContractInstanceId
 */
static getSizePrefixedRootAsContractInstanceId(bb:flatbuffers.ByteBuffer, obj?:ContractInstanceId):ContractInstanceId {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ContractInstanceId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
dataArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startContractInstanceId(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endContractInstanceId(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createContractInstanceId(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  ContractInstanceId.startContractInstanceId(builder);
  ContractInstanceId.addData(builder, dataOffset);
  return ContractInstanceId.endContractInstanceId(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class Key {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Key
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Key {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Key= obj
 * @returns Key
 */
static getRootAsKey(bb:flatbuffers.ByteBuffer, obj?:Key):Key {
  return (obj || new Key()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Key= obj
 * @returns Key
 */
static getSizePrefixedRootAsKey(bb:flatbuffers.ByteBuffer, obj?:Key):Key {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Key()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.ContractInstanceId= obj
 * @returns CommonDefinitions.ContractInstanceId|null
 */
instance(obj?:CommonDefinitions.ContractInstanceId):CommonDefinitions.ContractInstanceId|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param number index
 * @returns number
 */
code(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
codeLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
codeArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startKey(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset instanceOffset
 */
static addInstance(builder:flatbuffers.Builder, instanceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, instanceOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset codeOffset
 */
static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, codeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createCodeVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCodeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endKey(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createKey(builder:flatbuffers.Builder, instanceOffset:flatbuffers.Offset, codeOffset:flatbuffers.Offset):flatbuffers.Offset {
  Key.startKey(builder);
  Key.addInstance(builder, instanceOffset);
  Key.addCode(builder, codeOffset);
  return Key.endKey(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class ContractV1 {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ContractV1
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ContractV1 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ContractV1= obj
 * @returns ContractV1
 */
static getRootAsContractV1(bb:flatbuffers.ByteBuffer, obj?:ContractV1):ContractV1 {
  return (obj || new ContractV1()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ContractV1= obj
 * @returns ContractV1
 */
static getSizePrefixedRootAsContractV1(bb:flatbuffers.ByteBuffer, obj?:ContractV1):ContractV1 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ContractV1()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.Key= obj
 * @returns CommonDefinitions.Key|null
 */
key(obj?:CommonDefinitions.Key):CommonDefinitions.Key|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.Key()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
dataArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @returns number
 */
parameters(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
parametersLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
parametersArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
version():string|null
version(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
version(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startContractV1(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset parametersOffset
 */
static addParameters(builder:flatbuffers.Builder, parametersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, parametersOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createParametersVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startParametersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset versionOffset
 */
static addVersion(builder:flatbuffers.Builder, versionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, versionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endContractV1(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createContractV1(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset, parametersOffset:flatbuffers.Offset, versionOffset:flatbuffers.Offset):flatbuffers.Offset {
  ContractV1.startContractV1(builder);
  ContractV1.addKey(builder, keyOffset);
  ContractV1.addData(builder, dataOffset);
  ContractV1.addParameters(builder, parametersOffset);
  ContractV1.addVersion(builder, versionOffset);
  return ContractV1.endContractV1(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class ContractContainer {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ContractContainer
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ContractContainer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ContractContainer= obj
 * @returns ContractContainer
 */
static getRootAsContractContainer(bb:flatbuffers.ByteBuffer, obj?:ContractContainer):ContractContainer {
  return (obj || new ContractContainer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ContractContainer= obj
 * @returns ContractContainer
 */
static getSizePrefixedRootAsContractContainer(bb:flatbuffers.ByteBuffer, obj?:ContractContainer):ContractContainer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ContractContainer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns CommonDefinitions.WasmContract
 */
contractType():CommonDefinitions.WasmContract {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : CommonDefinitions.WasmContract.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
contract<T extends flatbuffers.Table>(obj:T):flatbuffers.Table|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startContractContainer(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param CommonDefinitions.WasmContract contractType
 */
static addContractType(builder:flatbuffers.Builder, contractType:CommonDefinitions.WasmContract) {
  builder.addFieldInt8(0, contractType, CommonDefinitions.WasmContract.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset contractOffset
 */
static addContract(builder:flatbuffers.Builder, contractOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contractOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endContractContainer(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createContractContainer(builder:flatbuffers.Builder, contractType:CommonDefinitions.WasmContract, contractOffset:flatbuffers.Offset):flatbuffers.Offset {
  ContractContainer.startContractContainer(builder);
  ContractContainer.addContractType(builder, contractType);
  ContractContainer.addContract(builder, contractOffset);
  return ContractContainer.endContractContainer(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class State {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns State
 */
__init(i:number, bb:flatbuffers.ByteBuffer):State {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param State= obj
 * @returns State
 */
static getRootAsState(bb:flatbuffers.ByteBuffer, obj?:State):State {
  return (obj || new State()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param State= obj
 * @returns State
 */
static getSizePrefixedRootAsState(bb:flatbuffers.ByteBuffer, obj?:State):State {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new State()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
dataArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startState(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endState(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createState(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  State.startState(builder);
  State.addData(builder, dataOffset);
  return State.endState(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class StateDelta {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StateDelta
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StateDelta {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateDelta= obj
 * @returns StateDelta
 */
static getRootAsStateDelta(bb:flatbuffers.ByteBuffer, obj?:StateDelta):StateDelta {
  return (obj || new StateDelta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateDelta= obj
 * @returns StateDelta
 */
static getSizePrefixedRootAsStateDelta(bb:flatbuffers.ByteBuffer, obj?:StateDelta):StateDelta {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateDelta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
dataArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStateDelta(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStateDelta(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStateDelta(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  StateDelta.startStateDelta(builder);
  StateDelta.addData(builder, dataOffset);
  return StateDelta.endStateDelta(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class StateSummary {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StateSummary
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StateSummary {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateSummary= obj
 * @returns StateSummary
 */
static getRootAsStateSummary(bb:flatbuffers.ByteBuffer, obj?:StateSummary):StateSummary {
  return (obj || new StateSummary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateSummary= obj
 * @returns StateSummary
 */
static getSizePrefixedRootAsStateSummary(bb:flatbuffers.ByteBuffer, obj?:StateSummary):StateSummary {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateSummary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Int8Array
 */
dataArray():Int8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStateSummary(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Int8Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createDataVector(builder:flatbuffers.Builder, data:number[]|Int8Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStateSummary(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStateSummary(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  StateSummary.startStateSummary(builder);
  StateSummary.addData(builder, dataOffset);
  return StateSummary.endStateSummary(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class StateUpdate {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StateUpdate
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StateUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateUpdate= obj
 * @returns StateUpdate
 */
static getRootAsStateUpdate(bb:flatbuffers.ByteBuffer, obj?:StateUpdate):StateUpdate {
  return (obj || new StateUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateUpdate= obj
 * @returns StateUpdate
 */
static getSizePrefixedRootAsStateUpdate(bb:flatbuffers.ByteBuffer, obj?:StateUpdate):StateUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.State= obj
 * @returns CommonDefinitions.State|null
 */
state(obj?:CommonDefinitions.State):CommonDefinitions.State|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStateUpdate(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stateOffset
 */
static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stateOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStateUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStateUpdate(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset):flatbuffers.Offset {
  StateUpdate.startStateUpdate(builder);
  StateUpdate.addState(builder, stateOffset);
  return StateUpdate.endStateUpdate(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class DeltaUpdate {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns DeltaUpdate
 */
__init(i:number, bb:flatbuffers.ByteBuffer):DeltaUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param DeltaUpdate= obj
 * @returns DeltaUpdate
 */
static getRootAsDeltaUpdate(bb:flatbuffers.ByteBuffer, obj?:DeltaUpdate):DeltaUpdate {
  return (obj || new DeltaUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param DeltaUpdate= obj
 * @returns DeltaUpdate
 */
static getSizePrefixedRootAsDeltaUpdate(bb:flatbuffers.ByteBuffer, obj?:DeltaUpdate):DeltaUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DeltaUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.StateDelta= obj
 * @returns CommonDefinitions.StateDelta|null
 */
delta(obj?:CommonDefinitions.StateDelta):CommonDefinitions.StateDelta|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.StateDelta()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startDeltaUpdate(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset deltaOffset
 */
static addDelta(builder:flatbuffers.Builder, deltaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, deltaOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endDeltaUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createDeltaUpdate(builder:flatbuffers.Builder, deltaOffset:flatbuffers.Offset):flatbuffers.Offset {
  DeltaUpdate.startDeltaUpdate(builder);
  DeltaUpdate.addDelta(builder, deltaOffset);
  return DeltaUpdate.endDeltaUpdate(builder);
}
}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class StateDeltaUpdate {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StateDeltaUpdate
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StateDeltaUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateDeltaUpdate= obj
 * @returns StateDeltaUpdate
 */
static getRootAsStateDeltaUpdate(bb:flatbuffers.ByteBuffer, obj?:StateDeltaUpdate):StateDeltaUpdate {
  return (obj || new StateDeltaUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateDeltaUpdate= obj
 * @returns StateDeltaUpdate
 */
static getSizePrefixedRootAsStateDeltaUpdate(bb:flatbuffers.ByteBuffer, obj?:StateDeltaUpdate):StateDeltaUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateDeltaUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.State= obj
 * @returns CommonDefinitions.State|null
 */
state(obj?:CommonDefinitions.State):CommonDefinitions.State|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.StateDelta= obj
 * @returns CommonDefinitions.StateDelta|null
 */
delta(obj?:CommonDefinitions.StateDelta):CommonDefinitions.StateDelta|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CommonDefinitions.StateDelta()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStateDeltaUpdate(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stateOffset
 */
static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stateOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset deltaOffset
 */
static addDelta(builder:flatbuffers.Builder, deltaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, deltaOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStateDeltaUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class StateWithContractInstanceUpdate {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StateWithContractInstanceUpdate
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StateWithContractInstanceUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateWithContractInstanceUpdate= obj
 * @returns StateWithContractInstanceUpdate
 */
static getRootAsStateWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:StateWithContractInstanceUpdate):StateWithContractInstanceUpdate {
  return (obj || new StateWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateWithContractInstanceUpdate= obj
 * @returns StateWithContractInstanceUpdate
 */
static getSizePrefixedRootAsStateWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:StateWithContractInstanceUpdate):StateWithContractInstanceUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.ContractInstanceId= obj
 * @returns CommonDefinitions.ContractInstanceId|null
 */
relatedTo(obj?:CommonDefinitions.ContractInstanceId):CommonDefinitions.ContractInstanceId|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.State= obj
 * @returns CommonDefinitions.State|null
 */
state(obj?:CommonDefinitions.State):CommonDefinitions.State|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CommonDefinitions.State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStateWithContractInstanceUpdate(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset relatedToOffset
 */
static addRelatedTo(builder:flatbuffers.Builder, relatedToOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, relatedToOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stateOffset
 */
static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stateOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStateWithContractInstanceUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class DeltaWithContractInstanceUpdate {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns DeltaWithContractInstanceUpdate
 */
__init(i:number, bb:flatbuffers.ByteBuffer):DeltaWithContractInstanceUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param DeltaWithContractInstanceUpdate= obj
 * @returns DeltaWithContractInstanceUpdate
 */
static getRootAsDeltaWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:DeltaWithContractInstanceUpdate):DeltaWithContractInstanceUpdate {
  return (obj || new DeltaWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param DeltaWithContractInstanceUpdate= obj
 * @returns DeltaWithContractInstanceUpdate
 */
static getSizePrefixedRootAsDeltaWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:DeltaWithContractInstanceUpdate):DeltaWithContractInstanceUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DeltaWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.ContractInstanceId= obj
 * @returns CommonDefinitions.ContractInstanceId|null
 */
relatedTo(obj?:CommonDefinitions.ContractInstanceId):CommonDefinitions.ContractInstanceId|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.StateDelta= obj
 * @returns CommonDefinitions.StateDelta|null
 */
delta(obj?:CommonDefinitions.StateDelta):CommonDefinitions.StateDelta|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CommonDefinitions.StateDelta()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startDeltaWithContractInstanceUpdate(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset relatedToOffset
 */
static addRelatedTo(builder:flatbuffers.Builder, relatedToOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, relatedToOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset deltaOffset
 */
static addDelta(builder:flatbuffers.Builder, deltaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, deltaOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endDeltaWithContractInstanceUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace CommonDefinitions{
export class StateDeltaWithContractInstanceUpdate {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StateDeltaWithContractInstanceUpdate
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StateDeltaWithContractInstanceUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateDeltaWithContractInstanceUpdate= obj
 * @returns StateDeltaWithContractInstanceUpdate
 */
static getRootAsStateDeltaWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:StateDeltaWithContractInstanceUpdate):StateDeltaWithContractInstanceUpdate {
  return (obj || new StateDeltaWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StateDeltaWithContractInstanceUpdate= obj
 * @returns StateDeltaWithContractInstanceUpdate
 */
static getSizePrefixedRootAsStateDeltaWithContractInstanceUpdate(bb:flatbuffers.ByteBuffer, obj?:StateDeltaWithContractInstanceUpdate):StateDeltaWithContractInstanceUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateDeltaWithContractInstanceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.ContractInstanceId= obj
 * @returns CommonDefinitions.ContractInstanceId|null
 */
relatedTo(obj?:CommonDefinitions.ContractInstanceId):CommonDefinitions.ContractInstanceId|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.State= obj
 * @returns CommonDefinitions.State|null
 */
state(obj?:CommonDefinitions.State):CommonDefinitions.State|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CommonDefinitions.State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.StateDelta= obj
 * @returns CommonDefinitions.StateDelta|null
 */
delta(obj?:CommonDefinitions.StateDelta):CommonDefinitions.StateDelta|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CommonDefinitions.StateDelta()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStateDeltaWithContractInstanceUpdate(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset relatedToOffset
 */
static addRelatedTo(builder:flatbuffers.Builder, relatedToOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, relatedToOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stateOffset
 */
static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stateOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset deltaOffset
 */
static addDelta(builder:flatbuffers.Builder, deltaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, deltaOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStateDeltaWithContractInstanceUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace HostResponseSchema{
export class HostError {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns HostError
 */
__init(i:number, bb:flatbuffers.ByteBuffer):HostError {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HostError= obj
 * @returns HostError
 */
static getRootAsHostError(bb:flatbuffers.ByteBuffer, obj?:HostError):HostError {
  return (obj || new HostError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HostError= obj
 * @returns HostError
 */
static getSizePrefixedRootAsHostError(bb:flatbuffers.ByteBuffer, obj?:HostError):HostError {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HostError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
cause():string|null
cause(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cause(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHostError(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset causeOffset
 */
static addCause(builder:flatbuffers.Builder, causeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, causeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHostError(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHostError(builder:flatbuffers.Builder, causeOffset:flatbuffers.Offset):flatbuffers.Offset {
  HostError.startHostError(builder);
  HostError.addCause(builder, causeOffset);
  return HostError.endHostError(builder);
}
}
}
/**
 * @constructor
 */
export namespace HostResponseSchema{
export class PutResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns PutResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PutResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param PutResponse= obj
 * @returns PutResponse
 */
static getRootAsPutResponse(bb:flatbuffers.ByteBuffer, obj?:PutResponse):PutResponse {
  return (obj || new PutResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param PutResponse= obj
 * @returns PutResponse
 */
static getSizePrefixedRootAsPutResponse(bb:flatbuffers.ByteBuffer, obj?:PutResponse):PutResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PutResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.Key= obj
 * @returns CommonDefinitions.Key|null
 */
key(obj?:CommonDefinitions.Key):CommonDefinitions.Key|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.Key()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPutResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPutResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPutResponse(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset):flatbuffers.Offset {
  PutResponse.startPutResponse(builder);
  PutResponse.addKey(builder, keyOffset);
  return PutResponse.endPutResponse(builder);
}
}
}
/**
 * @constructor
 */
export namespace HostResponseSchema{
export class UpdateResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns UpdateResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):UpdateResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UpdateResponse= obj
 * @returns UpdateResponse
 */
static getRootAsUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:UpdateResponse):UpdateResponse {
  return (obj || new UpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UpdateResponse= obj
 * @returns UpdateResponse
 */
static getSizePrefixedRootAsUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:UpdateResponse):UpdateResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.Key= obj
 * @returns CommonDefinitions.Key|null
 */
key(obj?:CommonDefinitions.Key):CommonDefinitions.Key|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.Key()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.StateSummary= obj
 * @returns CommonDefinitions.StateSummary|null
 */
summary(obj?:CommonDefinitions.StateSummary):CommonDefinitions.StateSummary|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CommonDefinitions.StateSummary()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startUpdateResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset summaryOffset
 */
static addSummary(builder:flatbuffers.Builder, summaryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, summaryOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endUpdateResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace HostResponseSchema{
export class GetResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GetResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GetResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetResponse= obj
 * @returns GetResponse
 */
static getRootAsGetResponse(bb:flatbuffers.ByteBuffer, obj?:GetResponse):GetResponse {
  return (obj || new GetResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetResponse= obj
 * @returns GetResponse
 */
static getSizePrefixedRootAsGetResponse(bb:flatbuffers.ByteBuffer, obj?:GetResponse):GetResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.Key= obj
 * @returns CommonDefinitions.Key|null
 */
key(obj?:CommonDefinitions.Key):CommonDefinitions.Key|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.Key()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.ContractContainer= obj
 * @returns CommonDefinitions.ContractContainer|null
 */
contract(obj?:CommonDefinitions.ContractContainer):CommonDefinitions.ContractContainer|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CommonDefinitions.ContractContainer()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param CommonDefinitions.State= obj
 * @returns CommonDefinitions.State|null
 */
state(obj?:CommonDefinitions.State):CommonDefinitions.State|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CommonDefinitions.State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGetResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset contractOffset
 */
static addContract(builder:flatbuffers.Builder, contractOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contractOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stateOffset
 */
static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, stateOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGetResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace HostResponseSchema{
export class UpdateNotification {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns UpdateNotification
 */
__init(i:number, bb:flatbuffers.ByteBuffer):UpdateNotification {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UpdateNotification= obj
 * @returns UpdateNotification
 */
static getRootAsUpdateNotification(bb:flatbuffers.ByteBuffer, obj?:UpdateNotification):UpdateNotification {
  return (obj || new UpdateNotification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UpdateNotification= obj
 * @returns UpdateNotification
 */
static getSizePrefixedRootAsUpdateNotification(bb:flatbuffers.ByteBuffer, obj?:UpdateNotification):UpdateNotification {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateNotification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param CommonDefinitions.Key= obj
 * @returns CommonDefinitions.Key|null
 */
key(obj?:CommonDefinitions.Key):CommonDefinitions.Key|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CommonDefinitions.Key()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @returns CommonDefinitions.UpdateData
 */
updateType():CommonDefinitions.UpdateData {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : CommonDefinitions.UpdateData.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
update<T extends flatbuffers.Table>(obj:T):flatbuffers.Table|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startUpdateNotification(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param CommonDefinitions.UpdateData updateType
 */
static addUpdateType(builder:flatbuffers.Builder, updateType:CommonDefinitions.UpdateData) {
  builder.addFieldInt8(1, updateType, CommonDefinitions.UpdateData.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset updateOffset
 */
static addUpdate(builder:flatbuffers.Builder, updateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, updateOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endUpdateNotification(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createUpdateNotification(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, updateType:CommonDefinitions.UpdateData, updateOffset:flatbuffers.Offset):flatbuffers.Offset {
  UpdateNotification.startUpdateNotification(builder);
  UpdateNotification.addKey(builder, keyOffset);
  UpdateNotification.addUpdateType(builder, updateType);
  UpdateNotification.addUpdate(builder, updateOffset);
  return UpdateNotification.endUpdateNotification(builder);
}
}
}
/**
 * @constructor
 */
export namespace HostResponseSchema{
export class HostResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns HostResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):HostResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HostResponse= obj
 * @returns HostResponse
 */
static getRootAsHostResponse(bb:flatbuffers.ByteBuffer, obj?:HostResponse):HostResponse {
  return (obj || new HostResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HostResponse= obj
 * @returns HostResponse
 */
static getSizePrefixedRootAsHostResponse(bb:flatbuffers.ByteBuffer, obj?:HostResponse):HostResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HostResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns HostResponseSchema.Response
 */
responseType():HostResponseSchema.Response {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : HostResponseSchema.Response.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
response<T extends flatbuffers.Table>(obj:T):flatbuffers.Table | null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHostResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param HostResponseSchema.Response responseType
 */
static addResponseType(builder:flatbuffers.Builder, responseType:HostResponseSchema.Response) {
  builder.addFieldInt8(0, responseType, HostResponseSchema.Response.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset responseOffset
 */
static addResponse(builder:flatbuffers.Builder, responseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, responseOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHostResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishHostResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedHostResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createHostResponse(builder:flatbuffers.Builder, responseType:HostResponseSchema.Response, responseOffset:flatbuffers.Offset):flatbuffers.Offset {
  HostResponse.startHostResponse(builder);
  HostResponse.addResponseType(builder, responseType);
  HostResponse.addResponse(builder, responseOffset);
  return HostResponse.endHostResponse(builder);
}
}
}
