// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ComponentKey, ComponentKeyT } from '../../schemas/client/component-key';


export class Component implements flatbuffers.IUnpackableObject<ComponentT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Component {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponent(bb:flatbuffers.ByteBuffer, obj?:Component):Component {
  return (obj || new Component()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponent(bb:flatbuffers.ByteBuffer, obj?:Component):Component {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Component()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

codeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

codeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

key(obj?:ComponentKey):ComponentKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ComponentKey()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startComponent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, codeOffset, 0);
}

static createCodeVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCodeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
}

static endComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): ComponentT {
  return new ComponentT(
    this.bb!.createScalarList<number>(this.code.bind(this), this.codeLength()),
    (this.key() !== null ? this.key()!.unpack() : null)
  );
}


unpackTo(_o: ComponentT): void {
  _o.code = this.bb!.createScalarList<number>(this.code.bind(this), this.codeLength());
  _o.key = (this.key() !== null ? this.key()!.unpack() : null);
}
}

export class ComponentT implements flatbuffers.IGeneratedObject {
constructor(
  public code: (number)[] = [],
  public key: ComponentKeyT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const code = Component.createCodeVector(builder, this.code);
  const key = (this.key !== null ? this.key!.pack(builder) : 0);

  Component.startComponent(builder);
  Component.addCode(builder, code);
  Component.addKey(builder, key);

  return Component.endComponent(builder);
}
}
