// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ApplicationMessage, ApplicationMessageT } from '../../schemas/client/application-message';
import { GetSecretResponse, GetSecretResponseT } from '../../schemas/client/get-secret-response';
import { InboundComponentMsgType, unionToInboundComponentMsgType, unionListToInboundComponentMsgType } from '../../schemas/client/inbound-component-msg-type';
import { RandomBytes, RandomBytesT } from '../../schemas/client/random-bytes';
import { UserResponse, UserResponseT } from '../../schemas/client/user-response';


export class InboundComponentMsg implements flatbuffers.IUnpackableObject<InboundComponentMsgT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InboundComponentMsg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInboundComponentMsg(bb:flatbuffers.ByteBuffer, obj?:InboundComponentMsg):InboundComponentMsg {
  return (obj || new InboundComponentMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInboundComponentMsg(bb:flatbuffers.ByteBuffer, obj?:InboundComponentMsg):InboundComponentMsg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InboundComponentMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

inboundType():InboundComponentMsgType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : InboundComponentMsgType.NONE;
}

inbound(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startInboundComponentMsg(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addInboundType(builder:flatbuffers.Builder, inboundType:InboundComponentMsgType) {
  builder.addFieldInt8(0, inboundType, InboundComponentMsgType.NONE);
}

static addInbound(builder:flatbuffers.Builder, inboundOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, inboundOffset, 0);
}

static endInboundComponentMsg(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInboundComponentMsg(builder:flatbuffers.Builder, inboundType:InboundComponentMsgType, inboundOffset:flatbuffers.Offset):flatbuffers.Offset {
  InboundComponentMsg.startInboundComponentMsg(builder);
  InboundComponentMsg.addInboundType(builder, inboundType);
  InboundComponentMsg.addInbound(builder, inboundOffset);
  return InboundComponentMsg.endInboundComponentMsg(builder);
}

unpack(): InboundComponentMsgT {
  return new InboundComponentMsgT(
    this.inboundType(),
    (() => {
      const temp = unionToInboundComponentMsgType(this.inboundType(), this.inbound.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: InboundComponentMsgT): void {
  _o.inboundType = this.inboundType();
  _o.inbound = (() => {
      const temp = unionToInboundComponentMsgType(this.inboundType(), this.inbound.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class InboundComponentMsgT implements flatbuffers.IGeneratedObject {
constructor(
  public inboundType: InboundComponentMsgType = InboundComponentMsgType.NONE,
  public inbound: ApplicationMessageT|GetSecretResponseT|RandomBytesT|UserResponseT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const inbound = builder.createObjectOffset(this.inbound);

  return InboundComponentMsg.createInboundComponentMsg(builder,
    this.inboundType,
    inbound
  );
}
}
