// automatically generated by the FlatBuffers compiler, do not modify

import { ApplicationMessage, ApplicationMessageT } from '../../schemas/client/application-message';
import { GetSecretResponse, GetSecretResponseT } from '../../schemas/client/get-secret-response';
import { RandomBytes, RandomBytesT } from '../../schemas/client/random-bytes';
import { UserResponse, UserResponseT } from '../../schemas/client/user-response';


export enum InboundComponentMsgType {
  NONE = 0,
  ApplicationMessage = 1,
  GetSecretResponse = 2,
  RandomBytes = 3,
  UserResponse = 4
}

export function unionToInboundComponentMsgType(
  type: InboundComponentMsgType,
  accessor: (obj:ApplicationMessage|GetSecretResponse|RandomBytes|UserResponse) => ApplicationMessage|GetSecretResponse|RandomBytes|UserResponse|null
): ApplicationMessage|GetSecretResponse|RandomBytes|UserResponse|null {
  switch(InboundComponentMsgType[type]) {
    case 'NONE': return null; 
    case 'ApplicationMessage': return accessor(new ApplicationMessage())! as ApplicationMessage;
    case 'GetSecretResponse': return accessor(new GetSecretResponse())! as GetSecretResponse;
    case 'RandomBytes': return accessor(new RandomBytes())! as RandomBytes;
    case 'UserResponse': return accessor(new UserResponse())! as UserResponse;
    default: return null;
  }
}

export function unionListToInboundComponentMsgType(
  type: InboundComponentMsgType, 
  accessor: (index: number, obj:ApplicationMessage|GetSecretResponse|RandomBytes|UserResponse) => ApplicationMessage|GetSecretResponse|RandomBytes|UserResponse|null, 
  index: number
): ApplicationMessage|GetSecretResponse|RandomBytes|UserResponse|null {
  switch(InboundComponentMsgType[type]) {
    case 'NONE': return null; 
    case 'ApplicationMessage': return accessor(index, new ApplicationMessage())! as ApplicationMessage;
    case 'GetSecretResponse': return accessor(index, new GetSecretResponse())! as GetSecretResponse;
    case 'RandomBytes': return accessor(index, new RandomBytes())! as RandomBytes;
    case 'UserResponse': return accessor(index, new UserResponse())! as UserResponse;
    default: return null;
  }
}
