// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ContractInstanceId, ContractInstanceIdT } from '../../schemas/client/contract-instance-id';
import { State, StateT } from '../../schemas/client/state';


export class RelatedContract implements flatbuffers.IUnpackableObject<RelatedContractT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RelatedContract {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRelatedContract(bb:flatbuffers.ByteBuffer, obj?:RelatedContract):RelatedContract {
  return (obj || new RelatedContract()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRelatedContract(bb:flatbuffers.ByteBuffer, obj?:RelatedContract):RelatedContract {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RelatedContract()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

instanceId(obj?:ContractInstanceId):ContractInstanceId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

state(obj?:State):State|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new State()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startRelatedContract(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addInstanceId(builder:flatbuffers.Builder, instanceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, instanceIdOffset, 0);
}

static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stateOffset, 0);
}

static endRelatedContract(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): RelatedContractT {
  return new RelatedContractT(
    (this.instanceId() !== null ? this.instanceId()!.unpack() : null),
    (this.state() !== null ? this.state()!.unpack() : null)
  );
}


unpackTo(_o: RelatedContractT): void {
  _o.instanceId = (this.instanceId() !== null ? this.instanceId()!.unpack() : null);
  _o.state = (this.state() !== null ? this.state()!.unpack() : null);
}
}

export class RelatedContractT implements flatbuffers.IGeneratedObject {
constructor(
  public instanceId: ContractInstanceIdT|null = null,
  public state: StateT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const instanceId = (this.instanceId !== null ? this.instanceId!.pack(builder) : 0);
  const state = (this.state !== null ? this.state!.pack(builder) : 0);

  RelatedContract.startRelatedContract(builder);
  RelatedContract.addInstanceId(builder, instanceId);
  RelatedContract.addState(builder, state);

  return RelatedContract.endRelatedContract(builder);
}
}
